import fs from 'node:fs';
import path from 'node:path';
import type { AdapterProfile } from './adapter.js';

export interface RuntimeConfig {
  daemonHost: string;
  daemonPort: number;
}

export function runtimeConfigFromEnv(env = process.env): RuntimeConfig {
  const daemonPort = Number.parseInt(env.AGENT_ORB_DAEMON_PORT ?? '17321', 10);
  if (!Number.isInteger(daemonPort) || daemonPort <= 0 || daemonPort > 65535) {
    throw new Error(`Invalid AGENT_ORB_DAEMON_PORT: ${env.AGENT_ORB_DAEMON_PORT}`);
  }

  return {
    daemonHost: env.AGENT_ORB_DAEMON_HOST ?? '127.0.0.1',
    daemonPort,
  };
}

export function writeConfig(configDir: string, selectedAdapters: AdapterProfile[], runtime = runtimeConfigFromEnv()): string {
  fs.mkdirSync(configDir, { recursive: true });
  const configPath = path.join(configDir, 'config.toml');
  const enabled = new Set(selectedAdapters.map((adapter) => adapter.name));

  const content = `# Generated by npx agent_orb\n\n[install]\nmethod = "npx"\nversion = "0.1.3"\n\n[adapters.codex]\nenabled = ${enabled.has('codex')}\nbinary = "codex"\nwrapper = "agent_orb-codex"\n\n[adapters.claude]\nenabled = ${enabled.has('claude')}\nbinary = "claude"\nwrapper = "agent_orb-claude"\n\n[daemon]\nhost = "${runtime.daemonHost}"\nport = ${runtime.daemonPort}\nauto_start = true\n\n[orb]\nposition = "top-right"\nsize = 36\nopacity = 0.88\nalways_on_top = true\nclick_through = false\n\n[colors]\ndisconnected = "#6B7280"\nidle = "#9CA3AF"\nstarting = "#60A5FA"\nactive = "#3B82F6"\nthinking_like = "#8B5CF6"\nwaiting_input = "#FBBF24"\ncompleted = "#22C55E"\nerror = "#EF4444"\nwarning = "#F97316"\n\n[behavior]\nsilent_threshold_seconds = 20\nstuck_threshold_seconds = 180\ncompleted_hold_seconds = 10\nerror_requires_click_to_clear = true\n\n[privacy]\ninclude_output_sample = false\nmax_sample_chars = 512\n`;

  fs.writeFileSync(configPath, content, 'utf8');
  return configPath;
}
